[View in Colaboratory](https://colab.research.google.com/github/Hyunjulie/DeepLearningZeroToAll/blob/master/lab6-1.ipynb)

In [0]:
import tensorflow as tf
tf.set_random_seed(800)

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]


In [0]:
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)



In [6]:
#Launch Session 
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  
  for step in range(2001):
    sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
    if step % 200 == 0: 
      print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
  
  print("--------------------")
  
  a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
  print(a, sess.run(tf.argmax(a,1)))
  
  print("--------------------")
  
  b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
  print(b, sess.run(tf.argmax(b,1)))
  
  print("--------------------")
  
  c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
  print(c, sess.run(tf.argmax(c,1)))
  
  print("--------------------")
  
  all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
  print(all, sess.run(tf.argmax(all,1)))

0 7.4833994
200 0.5682226
400 0.47262305
600 0.39840204
800 0.3296994
1000 0.25906333
1200 0.22154981
1400 0.20195496
1600 0.18542674
1800 0.17130804
2000 0.1591168
--------------------
[[1.3993281e-02 9.8599499e-01 1.1789086e-05]] [1]
--------------------
[[0.76292825 0.19966902 0.03740274]] [0]
--------------------
[[1.7130944e-08 3.7369854e-04 9.9962628e-01]] [2]
--------------------
[[1.3993281e-02 9.8599499e-01 1.1789087e-05]
 [7.6292825e-01 1.9966902e-01 3.7402745e-02]
 [1.7130946e-08 3.7369854e-04 9.9962628e-01]] [1 0 2]
